### ISSUE TITLE
Change text on beta banner

### ISSUE THREAD

**Issue by cweems** [codeforamerica/syracuse_biz_portal#184]
I don't think regular users will know what this means. Maybe "this site is currently under active development"

**Comment by millzpaugh** [comment]
Amanda and I discussed this with Nora and she came up with the text so I
think we should leave it.

**Comment by cweems** [comment]
I disagree! Let's talk it through tomorrow. It's also offsetting the login and profile view buttons.

**Comment by adamewood** [comment]
Hey guys, just jumping in to say that the "in beta" banner is there so city staff don't freak out when we send them a live link to the web. We expect to remove the banner before we start showing it to the public outside of usability testing, so I think it's ok to expose people to development jargon in that context. Can we move this to backlog, because there will be a time when we need to remove it (in 2 or 3 weeks) and we'll have to decide if that's an remove-and-replace or just removing? 

Also just bringing @racheledelman 's attention to the thread bc of the impact on the page layout at present.

**Comment by cweems** [comment]
I'd like to push that we do update this. Three reasons:
* We can make it more visible
* We can fix the layout issues it causes
* We can actually use it as a call to action for feedback

Here's what I'm proposing:
<img width="1280" alt="screen shot 2017-01-19 at 1 20 00 pm" src="https://cloud.githubusercontent.com/assets/1418949/22125871/475fb1a0-de4a-11e6-8411-ae249f9f3c75.png">

It will trigger the Zendesk chat when a user clicks on that link. I think should leave this up as long as we're making active changes – even when users are on the site, since we'll be in beta up until at least late march.
