### ISSUE TITLE
Update CoU messages

### ISSUE THREAD

**Issue by adamewood** [codeforamerica/syracuse_biz_portal#247]
-Change the text on departmental reviews:
Police Department
Does the business owner have a relevant and recent criminal conviction?

Parking Violations Bureau
Does the business or property owner have outstanding parking violations?

Department of Housing
Are there housing judgements against the property or business owner?

Department of Water
Does the business or property owner have delinquent water bills?

Bureau of Treasury
Does the property or business owner have outstanding taxes?

**Comment by racheledelman** [comment]
> Make sure that denial information includes Pam's number

This will be handled in #241 

> Can we also add information in the sidebar or elsewhere 

Is this a good location?
![image](https://cloud.githubusercontent.com/assets/2693690/23044100/9c534b1c-f453-11e6-93c2-85ae5736378c.png)

We can put it in an alert box like so:
![image](https://cloud.githubusercontent.com/assets/2693690/23044439/12e325a8-f455-11e6-8704-71c3d25557e3.png)

> if the property is found to be in violation during an inspection, a building permit may be required, and the business must be inspected again after the correction is made?

Is this language good/correct?

_If a violation is found during an inspection, it will need to be fixed. This may require a building permit. After the problem is fixed, the business must be inspected again_

**Comment by adamewood** [comment]
I was thinking this would be static and informational near the types of permits users can search for, but we can talk about it next week I guess. I'l add myself to the issue so we don't forget.

**Comment by racheledelman** [comment]
@adamewood did we come to a decision about where to put this language?
>If a violation is found during an inspection, it will need to be fixed. This may require a building permit. After the problem is fixed, the business must be inspected again
